---
- name: Install dependencies for building ruby on Ubuntu
  ansible.builtin.apt:
    state: present
    name:
      - build-essential
      - curl
      - git-core
      - libcurl4-openssl-dev
      - libffi-dev
      - libjemalloc-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - libyaml-dev
      - python3-software-properties
      - sqlite3
      - zlib1g-dev

- name: Install dependencies for building ruby on Ubuntu 22.04
  ansible.builtin.apt:
    pkg: ruby3.0
    state: present
  when: ansible_distribution_version == '22.04'
